export default [
  {
    id: '7ilnb77lk',
    name: 'John Smith',
    avatar: 'john-smith.jpg',
    role: 'Graphic designer',
    location: 'Rivera State 32/106',
    company: 'Twitter, Inc.',
    street: '795 Falson Ave',
    suite: 'Suite 600',
    city: 'San Francisco',
    state: 'CA',
    zip: '94107',
    phone: '(123) 456-7890',
  },
  {
    id: '7ilnb8pnj',
    name: 'Alex Johnatan',
    avatar: 'alex jonathan.jpg',
    role: 'CEO',
    location: 'Rivera State 32/106',
    company: 'Twitter, Inc.',
    street: '795 Falson Ave',
    suite: 'Suite 600',
    city: 'San Francisco',
    state: 'CA',
    zip: '94107',
    phone: '(123) 456-7890',
  },
  {
    id: '7ilnb9b2e',
    name: 'Monica Smith',
    avatar: 'monica smith.jpg',
    role: 'Marketing manager',
    location: 'Rivera State 32/106',
    company: 'Twitter, Inc.',
    street: '795 Falson Ave',
    suite: 'Suite 600',
    city: 'San Francisco',
    state: 'CA',
    zip: '94107',
    phone: '(123) 456-7890',
  },
  {
    id: '7ilnb9lli',
    name: 'Michael Zimber',
    avatar: 'michael zimber.jpg',
    role: 'Sales manager',
    location: 'Rivera State 32/106',
    company: 'Twitter, Inc.',
    street: '795 Falson Ave',
    suite: 'Suite 600',
    city: 'San Francisco',
    state: 'CA',
    zip: '94107',
    phone: '(123) 456-7890',
  },
  {
    id: '7ilnba5gd',
    name: 'Sandra Smith',
    avatar: 'sandra smith.jpg',
    role: 'Graphic designer',
    location: 'Rivera State 32/106',
    company: 'Twitter, Inc.',
    street: '795 Falson Ave',
    suite: 'Suite 600',
    city: 'San Francisco',
    state: 'CA',
    zip: '94107',
    phone: '(123) 456-7890',
  },
  {
    id: '7ilnbagfj',
    name: 'Janeth Carton',
    avatar: 'janeth carton.jpg',
    role: 'Graphic designer',
    location: 'Rivera State 32/106',
    company: 'Twitter, Inc.',
    street: '795 Falson Ave',
    suite: 'Suite 600',
    city: 'San Francisco',
    state: 'CA',
    zip: '94107',
    phone: '(123) 456-7890',
  },
]